export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  sold: number
  discount?: number
  location?: string
  freeShip?: boolean
  category?: string
}

export const featuredProducts: Product[] = [
  // Điện thoại & Phụ kiện
  {
    id: "1",
    name: "Điện Thoại Samsung Galaxy S24 Ultra 256GB",
    price: 29990000,
    originalPrice: 33990000,
    image: "/samsung-galaxy-s24-ultra.png",
    rating: 4.9,
    sold: 1234,
    discount: 12,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "2",
    name: "iPhone 15 Pro Max 256GB Chính Hãng VN/A",
    price: 32990000,
    originalPrice: 34990000,
    image: "/iphone-15-pro-max-display.png",
    rating: 5.0,
    sold: 2341,
    discount: 6,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "3",
    name: "Xiaomi 14 Ultra 5G 512GB Camera Leica",
    price: 24990000,
    originalPrice: 27990000,
    image: "/xiaomi-14-ultra.jpg",
    rating: 4.8,
    sold: 892,
    discount: 11,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "4",
    name: "Tai Nghe Bluetooth AirPods Pro 2 USB-C",
    price: 5990000,
    originalPrice: 6990000,
    image: "/airpods-pro-2.png",
    rating: 4.9,
    sold: 3456,
    discount: 14,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "5",
    name: "Tai Nghe Gaming Razer BlackShark V2 Pro",
    price: 3990000,
    originalPrice: 4990000,
    image: "/razer-blackshark-gaming-headset.jpg",
    rating: 4.7,
    sold: 678,
    discount: 20,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "6",
    name: "Ốp Lưng iPhone 15 Pro Max Silicone MagSafe",
    price: 890000,
    originalPrice: 1290000,
    image: "/iphone-case-magsafe.jpg",
    rating: 4.6,
    sold: 5678,
    discount: 31,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "7",
    name: "Cáp Sạc Nhanh Type-C 100W Dài 2m",
    price: 149000,
    originalPrice: 299000,
    image: "/usb-c-cable-fast-charging.jpg",
    rating: 4.5,
    sold: 8901,
    discount: 50,
    location: "Hà Nội",
    freeShip: false,
    category: "Điện thoại & Phụ kiện",
  },
  {
    id: "8",
    name: "Sạc Dự Phòng Anker 20000mAh PD 65W",
    price: 1290000,
    originalPrice: 1790000,
    image: "/anker-power-bank.jpg",
    rating: 4.8,
    sold: 2109,
    discount: 28,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện thoại & Phụ kiện",
  },

  // Thời trang
  {
    id: "9",
    name: "Áo Thun Nam Cotton 100% Form Rộng Unisex",
    price: 89000,
    originalPrice: 150000,
    image: "/plain-white-tshirt.png",
    rating: 4.8,
    sold: 12341,
    discount: 41,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Thời trang",
  },
  {
    id: "10",
    name: "Quần Jean Nam Slim Fit Co Giãn Cao Cấp",
    price: 249000,
    originalPrice: 450000,
    image: "/blue-jeans-slim-fit.jpg",
    rating: 4.7,
    sold: 5678,
    discount: 45,
    location: "Hà Nội",
    freeShip: true,
    category: "Thời trang",
  },
  {
    id: "11",
    name: "Áo Sơ Mi Nam Dài Tay Oxford Trắng",
    price: 179000,
    originalPrice: 320000,
    image: "/white-oxford-shirt.png",
    rating: 4.6,
    sold: 3456,
    discount: 44,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thời trang",
  },
  {
    id: "12",
    name: "Váy Nữ Dáng Dài Hoa Nhí Vintage Retro",
    price: 199000,
    originalPrice: 380000,
    image: "/floral-vintage-dress.jpg",
    rating: 4.9,
    sold: 4567,
    discount: 48,
    location: "Hà Nội",
    freeShip: true,
    category: "Thời trang",
  },
  {
    id: "13",
    name: "Áo Khoác Hoodie Nỉ Ngoại Form Rộng",
    price: 299000,
    originalPrice: 550000,
    image: "/oversized-hoodie.png",
    rating: 4.8,
    sold: 6789,
    discount: 46,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Thời trang",
  },
  {
    id: "14",
    name: "Quần Short Kaki Nam Túi Hộp Cao Cấp",
    price: 159000,
    originalPrice: 280000,
    image: "/khaki-cargo-shorts.jpg",
    rating: 4.5,
    sold: 2345,
    discount: 43,
    location: "Hà Nội",
    freeShip: false,
    category: "Thời trang",
  },
  {
    id: "15",
    name: "Đầm Công Sở Nữ Tay Lỡ Thanh Lịch",
    price: 279000,
    originalPrice: 520000,
    image: "/office-dress-elegant.jpg",
    rating: 4.7,
    sold: 1890,
    discount: 46,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Thời trang",
  },
  {
    id: "16",
    name: "Giày Thể Thao Nam Nữ Sneaker Trắng Đế Cao",
    price: 199000,
    originalPrice: 350000,
    image: "/white-sneakers-platform.jpg",
    rating: 4.9,
    sold: 8901,
    discount: 43,
    location: "Hà Nội",
    freeShip: true,
    category: "Thời trang",
  },

  // Làm đẹp
  {
    id: "17",
    name: "Son Kem Lì 3CE Velvet Lip Tint Hàn Quốc",
    price: 189000,
    originalPrice: 350000,
    image: "/assorted-lipsticks.png",
    rating: 4.9,
    sold: 7890,
    discount: 46,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Làm đẹp",
  },
  {
    id: "18",
    name: "Kem Chống Nắng SPF50+ PA++++ La Roche-Posay",
    price: 389000,
    originalPrice: 520000,
    image: "/sunscreen-la-roche-posay.jpg",
    rating: 5.0,
    sold: 5678,
    discount: 25,
    location: "Hà Nội",
    freeShip: true,
    category: "Làm đẹp",
  },
  {
    id: "19",
    name: "Serum Vitamin C The Ordinary 30ml",
    price: 279000,
    originalPrice: 450000,
    image: "/vitamin-c-serum.png",
    rating: 4.8,
    sold: 4567,
    discount: 38,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Làm đẹp",
  },
  {
    id: "20",
    name: "Mặt Nạ Giấy Mediheal N.M.F Aquaring 10 Miếng",
    price: 159000,
    originalPrice: 280000,
    image: "/mediheal-sheet-mask.jpg",
    rating: 4.7,
    sold: 6789,
    discount: 43,
    location: "Hà Nội",
    freeShip: false,
    category: "Làm đẹp",
  },
  {
    id: "21",
    name: "Sữa Rửa Mặt CeraVe Foaming Cleanser 473ml",
    price: 299000,
    originalPrice: 450000,
    image: "/cerave-cleanser.jpg",
    rating: 4.9,
    sold: 3456,
    discount: 34,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Làm đẹp",
  },
  {
    id: "22",
    name: "Nước Hoa Hồng Klairs Supple Preparation 180ml",
    price: 349000,
    originalPrice: 520000,
    image: "/klairs-toner.jpg",
    rating: 4.8,
    sold: 2345,
    discount: 33,
    location: "Hà Nội",
    freeShip: true,
    category: "Làm đẹp",
  },
  {
    id: "23",
    name: "Kem Dưỡng Ẩm Neutrogena Hydro Boost 50g",
    price: 249000,
    originalPrice: 380000,
    image: "/neutrogena-hydro-boost.jpg",
    rating: 4.7,
    sold: 4567,
    discount: 34,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Làm đẹp",
  },
  {
    id: "24",
    name: "Phấn Nước Cushion Laneige Neo 15g",
    price: 459000,
    originalPrice: 680000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 5678,
    discount: 33,
    location: "Hà Nội",
    freeShip: true,
    category: "Làm đẹp",
  },

  // Đồ gia dụng
  {
    id: "25",
    name: "Nồi Chiên Không Dầu 5.5L Philips HD9252",
    price: 2490000,
    originalPrice: 3990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 1234,
    discount: 38,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Đồ gia dụng",
  },
  {
    id: "26",
    name: "Máy Hút Bụi Không Dây Dyson V11 Absolute",
    price: 14990000,
    originalPrice: 18990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 567,
    discount: 21,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ gia dụng",
  },
  {
    id: "27",
    name: "Máy Lọc Không Khí Xiaomi 4 Pro",
    price: 3990000,
    originalPrice: 5490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 892,
    discount: 27,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Đồ gia dụng",
  },
  {
    id: "28",
    name: "Bộ Nồi Inox 304 Cao Cấp 5 Món",
    price: 1290000,
    originalPrice: 2490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 1456,
    discount: 48,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ gia dụng",
  },
  {
    id: "29",
    name: "Máy Xay Sinh Tố Philips HR2222 600W",
    price: 890000,
    originalPrice: 1490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    sold: 2109,
    discount: 40,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Đồ gia dụng",
  },
  {
    id: "30",
    name: "Bình Đun Siêu Tốc Inox 1.8L Sunhouse",
    price: 349000,
    originalPrice: 590000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    sold: 3456,
    discount: 41,
    location: "Hà Nội",
    freeShip: false,
    category: "Đồ gia dụng",
  },
  {
    id: "31",
    name: "Máy Hút Ẩm Electrolux EDH12TRFW 12L",
    price: 4990000,
    originalPrice: 6990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 678,
    discount: 29,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Đồ gia dụng",
  },
  {
    id: "32",
    name: "Bộ Chảo Chống Dính Ceramic 3 Món",
    price: 599000,
    originalPrice: 1190000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 2345,
    discount: 50,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ gia dụng",
  },

  // Thực phẩm
  {
    id: "33",
    name: "Cà Phê Rang Xay Trung Nguyên Legend 500g",
    price: 189000,
    originalPrice: 250000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 5678,
    discount: 24,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "34",
    name: "Mật Ong Rừng Nguyên Chất 500ml",
    price: 249000,
    originalPrice: 380000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 3456,
    discount: 34,
    location: "Hà Nội",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "35",
    name: "Yến Mạch Úc Quaker Oats 1kg",
    price: 129000,
    originalPrice: 180000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 4567,
    discount: 28,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "36",
    name: "Hạt Điều Rang Muối Cao Cấp 500g",
    price: 179000,
    originalPrice: 280000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 2345,
    discount: 36,
    location: "Hà Nội",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "37",
    name: "Dầu Ô Liu Extra Virgin Bertolli 500ml",
    price: 299000,
    originalPrice: 450000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 1890,
    discount: 34,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "38",
    name: "Nước Mắm Phú Quốc 584 Chai 500ml",
    price: 89000,
    originalPrice: 120000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 6789,
    discount: 26,
    location: "Hà Nội",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "39",
    name: "Trà Xanh Matcha Nhật Bản 100g",
    price: 349000,
    originalPrice: 520000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 2109,
    discount: 33,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thực phẩm",
  },
  {
    id: "40",
    name: "Gạo ST25 Thơm Ngon Cao Cấp 5kg",
    price: 189000,
    originalPrice: 250000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 8901,
    discount: 24,
    location: "Hà Nội",
    freeShip: true,
    category: "Thực phẩm",
  },

  // Sách & Văn phòng phẩm
  {
    id: "41",
    name: "Sách Đắc Nhân Tâm - Dale Carnegie",
    price: 79000,
    originalPrice: 120000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 12341,
    discount: 34,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "42",
    name: "Sách Nhà Giả Kim - Paulo Coelho",
    price: 69000,
    originalPrice: 100000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 10234,
    discount: 31,
    location: "Hà Nội",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "43",
    name: "Bút Bi Thiên Long TL-079 Hộp 20 Cây",
    price: 39000,
    originalPrice: 60000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 8901,
    discount: 35,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "44",
    name: "Sổ Tay Bìa Da A5 Cao Cấp 200 Trang",
    price: 89000,
    originalPrice: 150000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 4567,
    discount: 41,
    location: "Hà Nội",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "45",
    name: "Bộ Bút Màu Stabilo Point 88 - 30 Màu",
    price: 449000,
    originalPrice: 650000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 2345,
    discount: 31,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "46",
    name: "Máy Tính Casio FX-580VN X Chính Hãng",
    price: 549000,
    originalPrice: 750000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 3456,
    discount: 27,
    location: "Hà Nội",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "47",
    name: "Giấy A4 Double A 70gsm 500 Tờ",
    price: 89000,
    originalPrice: 120000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 6789,
    discount: 26,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },
  {
    id: "48",
    name: "Bìa Kẹp Tài Liệu A4 Deli Hộp 12 Cái",
    price: 59000,
    originalPrice: 90000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    sold: 5678,
    discount: 34,
    location: "Hà Nội",
    freeShip: false,
    category: "Sách & Văn phòng phẩm",
  },

  // Thể thao
  {
    id: "49",
    name: "Thảm Tập Yoga TPE 2 Lớp Dày 8mm",
    price: 299000,
    originalPrice: 550000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 3456,
    discount: 46,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Thể thao",
  },
  {
    id: "50",
    name: "Bóng Đá Động Lực UHV 2.07 FIFA Quality",
    price: 349000,
    originalPrice: 520000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 2345,
    discount: 33,
    location: "Hà Nội",
    freeShip: false,
    category: "Thể thao",
  },
  {
    id: "51",
    name: "Găng Tay Tập Gym Cao Cấp Có Bảo Vệ Cổ Tay",
    price: 149000,
    originalPrice: 280000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 4567,
    discount: 47,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thể thao",
  },
  {
    id: "52",
    name: "Vợt Cầu Lông Yonex Astrox 99 Pro",
    price: 3990000,
    originalPrice: 5490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 892,
    discount: 27,
    location: "Hà Nội",
    freeShip: true,
    category: "Thể thao",
  },
  {
    id: "53",
    name: "Bình Lắc Protein Shaker 700ml BPA Free",
    price: 89000,
    originalPrice: 150000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    sold: 5678,
    discount: 41,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Thể thao",
  },
  {
    id: "54",
    name: "Dây Kháng Lực Tập Gym 5 Mức Độ",
    price: 179000,
    originalPrice: 320000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 3456,
    discount: 44,
    location: "Hà Nội",
    freeShip: false,
    category: "Thể thao",
  },
  {
    id: "55",
    name: "Giày Chạy Bộ Nike Air Zoom Pegasus 40",
    price: 2990000,
    originalPrice: 3990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 1890,
    discount: 25,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Thể thao",
  },
  {
    id: "56",
    name: "Bộ Tạ Tay Cao Su 2kg x 2 Cái",
    price: 249000,
    originalPrice: 380000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 2109,
    discount: 34,
    location: "Hà Nội",
    freeShip: false,
    category: "Thể thao",
  },

  // Đồ chơi
  {
    id: "57",
    name: "Lego Technic Lamborghini Sián 3696 Chi Tiết",
    price: 9990000,
    originalPrice: 12990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 567,
    discount: 23,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Đồ chơi",
  },
  {
    id: "58",
    name: "Rubik 3x3 MoYu RS3M 2021 Magnetic",
    price: 189000,
    originalPrice: 320000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 3456,
    discount: 41,
    location: "Hà Nội",
    freeShip: false,
    category: "Đồ chơi",
  },
  {
    id: "59",
    name: "Búp Bê Barbie Dreamhouse Adventures",
    price: 449000,
    originalPrice: 680000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 2345,
    discount: 34,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Đồ chơi",
  },
  {
    id: "60",
    name: "Xe Điều Khiển Từ Xa Buggy 4WD 1:16",
    price: 599000,
    originalPrice: 990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    sold: 1890,
    discount: 39,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ chơi",
  },
  {
    id: "61",
    name: "Bộ Đồ Chơi Nấu Ăn 36 Món Cho Bé",
    price: 249000,
    originalPrice: 450000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    sold: 4567,
    discount: 45,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Đồ chơi",
  },
  {
    id: "62",
    name: "Mô Hình Gundam RG 1/144 Nu Gundam",
    price: 890000,
    originalPrice: 1290000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 1234,
    discount: 31,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ chơi",
  },
  {
    id: "63",
    name: "Bộ Xếp Hình Nam Châm 100 Chi Tiết",
    price: 349000,
    originalPrice: 590000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 3456,
    discount: 41,
    location: "TP. Hồ Chí Minh",
    freeShip: false,
    category: "Đồ chơi",
  },
  {
    id: "64",
    name: "Gấu Bông Teddy Bear Khổng Lồ 1.2m",
    price: 599000,
    originalPrice: 990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 2109,
    discount: 39,
    location: "Hà Nội",
    freeShip: true,
    category: "Đồ chơi",
  },

  // Điện tử
  {
    id: "65",
    name: "Laptop Dell XPS 13 9340 i7 32GB 1TB",
    price: 42990000,
    originalPrice: 49990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 456,
    discount: 14,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "66",
    name: "MacBook Air M3 13 inch 16GB 512GB",
    price: 32990000,
    originalPrice: 36990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 892,
    discount: 11,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "67",
    name: "iPad Pro M4 11 inch WiFi 256GB",
    price: 24990000,
    originalPrice: 27990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 678,
    discount: 11,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "68",
    name: "Màn Hình Gaming LG UltraGear 27 inch 240Hz",
    price: 7990000,
    originalPrice: 10990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 1234,
    discount: 27,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "69",
    name: "Bàn Phím Cơ Keychron K8 Pro RGB Hot-swap",
    price: 2490000,
    originalPrice: 3490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 2345,
    discount: 29,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "70",
    name: "Chuột Không Dây Logitech MX Master 3S",
    price: 2290000,
    originalPrice: 2990000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    sold: 1890,
    discount: 23,
    location: "Hà Nội",
    freeShip: false,
    category: "Điện tử",
  },
  {
    id: "71",
    name: "Webcam Logitech Brio 4K Ultra HD",
    price: 4990000,
    originalPrice: 6490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    sold: 892,
    discount: 23,
    location: "TP. Hồ Chí Minh",
    freeShip: true,
    category: "Điện tử",
  },
  {
    id: "72",
    name: "Ổ Cứng SSD Samsung 990 Pro 2TB NVMe",
    price: 5490000,
    originalPrice: 7490000,
    image: "/placeholder.svg?height=400&width=400",
    rating: 5.0,
    sold: 1456,
    discount: 27,
    location: "Hà Nội",
    freeShip: true,
    category: "Điện tử",
  },
]

export const products = featuredProducts
